language: python
python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

env:
  global:
    - 'APP_SETTINGS'='testing'

before_script:
  - psql -c 'CREATE DATABASE testingdb;' -U postgres
 
script: 
  - nosetests --with-coverage --cover-package=storeapp

after_success: 
  - coveralls
