language: python
python:
  - "3.6"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to tell travis to install postgresql database 
# and create a test database called testingdb
before_script:
  - psql -c 'CREATE DATABASE testingdb;' -U postgres

# command to run tests 
script: 
  - python -m pytest --cov=app tests/

after_success: 
  - coveralls